library("mlr3")
library("mlr3pipelines")

testdat = data[1:20,]
task = as_task_regr(testdat, target = "costpd")
task$data()

preprocess_feature_age_fct = function(data, option){ 
  if(option == "A"){
    # Option A ---- 
    # Leave age as continuous variable
    data = data
  } else if(option == "B"){
    # Option B ---- 
    # Categorize age (= factor variable, but not ordered factor!)
    data = data %>% 
      mutate(age =  cut(age, breaks = c(26,seq(50,90,10),102), include.lowest = TRUE ))
    stopifnot(sum(is.na(data$age))==0) # make sure that no NAs were generated by transformation
  }
  return(data)
}

testfct = function(data) {
  data = data %>% 
    mutate(age =  cut(age, breaks = c(26,seq(50,90,10),102), include.lowest = TRUE ))
  stopifnot(sum(is.na(data$age))==0) # make sure that no NAs were generated by transformation
  return(data)
}


PipeOpPreprocFeatureAge = R6::R6Class("PipeOpPreprocFeatureAge",
                                inherit = mlr3pipelines::PipeOpTaskPreprocSimple,
                                public = list(
                                  initialize = function(id = "preproc.feature.age", param_vals = list()) {
                                    ps = ParamSet$new(params = list(
                                      ParamFct$new("option", levels = c("A", "B"))
                                    ))
                                    ps$values = list(option = "A")
                                    super$initialize(id = id, param_set = ps, 
                                                     param_vals = param_vals)
                                  }
                                ),
                            
                          
                                
                                # public = list(
                                #   initialize = function(id = "preproc.feature.age") {
                                #     param_set = ps(
                                #      option =  p_fct(c("A", "B"))       )
                                #     
                                #     super$initialize(id = id,
                                #                      param_set = param_set)
                                #   }
                                # ),
                                private = list(
                                  .transform_dt = function(dt, levels) {
                                #    pars = self$param_set$get_values()
                                    invoke(
                                      preprocess_feature_age_fct,
                                      data = dt,
                                      option=self$param_set$values$option)
                                  }
                                )
)
gr = Graph$new()$add_pipeop(PipeOpPreprocFeatureAge$new())
result_posa = gr$train(task)[[1]]
t=result_posa$data()

ptest = PipeOpPreprocFeatureAge$new()
ptest$param_set$values$option = "B"
ptest$train(list(task))[[1]]$data() ###!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

#https://mlr3pipelines.mlr-org.com/reference/mlr_pipeops_colapply.html
# https://github.com/mlr-org/mlr3pipelines/blob/master/R/PipeOpColApply.R
#https://rdrr.io/github/mlr-org/mlr3pipelines/src/R/PipeOpEncode.R
